In [2]:
import sys
import os                           # for os interface
import csv
import math
import pickle                       # for full-precision data storage
import numpy as np
import pandas as pd
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
from collections import OrderedDict, defaultdict  # append list to disc
import timeit

In [3]:
start_time = timeit.default_timer()
data_file = '../input/indiv18/itcont.txt'
test_data = '../input/indiv18/test_data.txt'
header_file = '../input/indiv_header_file.csv'
elapsed = timeit.default_timer() - start_time
print (elapsed)

7.639199611730874e-05

In [4]:
start_time = timeit.default_timer()
# read header line
indiv_header=[]
with open(header_file) as f:
    for line in f:
        header_ele=[ele.strip() for ele in line.split(',') ]
        indiv_header.extend(header_ele) # use extend instead of append
elapsed = timeit.default_timer() - start_time
print (elapsed)
dataset_raw = pd.read_csv(test_data,delimiter='|',\
                      names=indiv_header,keep_default_na=False,dtype=str)
elapsed = timeit.default_timer() - start_time
print (elapsed)

0.0032961949982563965
0.02503703899856191

In [5]:
start_time = timeit.default_timer()
# keep columns of interest
dataset_valid=pd.DataFrame()
dataset_valid=dataset_raw.drop(['AMNDT_IND', 'RPT_TP','TRANSACTION_PGI',\
              'IMAGE_NUM','TRANSACTION_TP','ENTITY_TP',\
              'CITY','STATE','EMPLOYER','OCCUPATION','TRAN_ID',
              'FILE_NUM','MEMO_CD','MEMO_TEXT','SUB_ID'], axis=1)

dataset_valid=dataset_valid[dataset_valid['OTHER_ID'].notnull()]
dataset_valid=dataset_valid[dataset_valid.notnull()]
elapsed = timeit.default_timer() - start_time
print (elapsed)

0.04419308900105534

In [6]:
start_time = timeit.default_timer()
# take the first five characters of 'ZIP_CODE'
# dataset_valid['ZIP_CODE']=dataset_valid['ZIP_CODE'].astype(str).str[0:5]
# 'ZIP_CODE' is valid only when the resulting string length is 5
dataset_valid=dataset_valid[dataset_valid['ZIP_CODE'].str.len()>=5]

# take integer in 'TRANSACTION_AMT'
dataset_valid['TRANSACTION_AMT']=dataset_valid['TRANSACTION_AMT'].astype(int)
# 'TRANSACTION_AMT' is valid only when > 0
dataset_valid=dataset_valid[dataset_valid['TRANSACTION_AMT']>5]

# first : Mark duplicates as True except for the first occurrence.
dataset_repeat=dataset_valid[dataset_valid.duplicated\
                             (['NAME','ZIP_CODE'],keep='first')]

elapsed = timeit.default_timer() - start_time
print (elapsed)

0.05846323999867309

In [7]:
dataset_repeat.iloc[0]

CMTE_ID                  C00394973
NAME               CAFARO, CAPRI S
ZIP_CODE                     44425
TRANSACTION_DT            01102017
TRANSACTION_AMT                396
OTHER_ID                 H4OH14094
Name: 109, dtype: object

In [8]:
start_time = timeit.default_timer()
dataset_arrange=pd.DataFrame()
dataset_arrange['Identity'] = dataset_repeat['CMTE_ID'] + dataset_repeat.ZIP_CODE.str[0:5] + dataset_repeat.TRANSACTION_DT.str[-4:]
dataset_arrange['TRANS_AMT'] = dataset_repeat.TRANSACTION_AMT
dataset_arrange['index1'] = dataset_arrange.index
elapsed = timeit.default_timer() - start_time
print (elapsed)

0.004079337006260175

In [22]:
dataset_arrange.iloc[0:5]

               Identity  TRANS_AMT  index1
109  C00394973444252017        396     109
110  C00394973444252017         25     110
124  C00104083170502017        190     124
208  C00610436995072017        500     208
215  C00161414352432017        125     215

In [ ]:
#dataset_arrange.groupby('Identity').expanding(1).TRANS_AMT.sum()
#grouped=dataset_arrange.groupby('Identity')['TRANS_AMT']
grouped=dataset_arrange.groupby('Identity')
#grouped.describe()
#grouped.groups['C00193433615252017']
#for name, group in grouped:
#   print (group)

In [148]:
start_time = timeit.default_timer()
#pd.rolling_quantile(grouped['TRANS_AMT'], 2, 0.3)
#s=grouped['TRANS_AMT']
#perc=grouped['TRANS_AMT'].expanding(min_periods=1,center=False).quantile(quantile=0.3)
#total=grouped['TRANS_AMT'].expanding(1).sum()
#times=grouped['TRANS_AMT'].expanding(1).count()

#grouped.groups.keys()
#grouped['TRANS_AMT'].apply(lambda x: x.describe())
#def func(x):
#    x['perc'] = x.expanding(window=1,center=False).quantile(quantile=0.3)
#    x['total'] = x.expanding(1).sum()
#    x['times'] = x.expanding(1).count()
#    return x
#grouped['TRANS_AMT'].apply(func)
def f(group):
    return pd.DataFrame({'Identity': group['Identity'], 'Perc': group['TRANS_AMT'].expanding(min_periods=1, center=False).quantile(quantile=0.3),\
                         'Total': group['TRANS_AMT'].expanding(1).sum(), 'Times': group['TRANS_AMT'].expanding(1).count()})

X=grouped.apply(f)

elapsed = timeit.default_timer() - start_time
print(elapsed)

In [149]:
X

               Identity    Perc  Times   Total
109  C00394973444252017   396.0    1.0   396.0
110  C00394973444252017   136.3    2.0   421.0
124  C00104083170502017   190.0    1.0   190.0
208  C00610436995072017   500.0    1.0   500.0
215  C00161414352432017   125.0    1.0   125.0
217  C00161414352162017   174.0    1.0   174.0
219  C00161414352422017   223.0    1.0   223.0
221  C00161414352232017   375.0    1.0   375.0
223  C00161414352422017   213.2    2.0   432.0
225  C00161414352232017   450.0    2.0  1000.0
228  C00161414452452017   208.0    1.0   208.0
249  C00275529782662017   536.0    1.0   536.0
264  C00035691802022017   205.0    1.0   205.0
267  C00035691770722017   208.0    1.0   208.0
269  C00035691770722017   208.0    2.0   416.0
271  C00035691770722017   208.0    3.0   624.0
275  C00035691770322017   208.0    1.0   208.0
280  C00035691770422017   190.0    1.0   190.0
296  C00415026200062017   208.0    1.0   208.0
317  C00364778100362017   210.0    1.0   210.0
319  C00364778100362017   208.6    2.0   418.0
322  C00364778100362017   140.8    3.0   458.0
499  C00365502282772017   208.0    1.0   208.0
502  C00365502245032017   208.0    1.0   208.0
504  C00365502245512017   208.0    1.0   208.0
506  C00365502443332017   208.0    1.0   208.0
519  C00033555317922017    96.0    1.0    96.0
543  C00089136232262017   208.0    1.0   208.0
547  C00089136223042017   208.0    1.0   208.0
552  C00089136232262017   208.0    2.0   416.0
..                  ...     ...    ...     ...
679  C00035006945832017   208.0   30.0  6240.0
681  C00035006945832017   208.0   31.0  6448.0
684  C00035006945832017   208.0   32.0  6656.0
686  C00035006945832017   208.0   33.0  6864.0
687  C00035006945832017   208.0   34.0  7072.0
689  C00035006945832017   208.0   35.0  7280.0
694  C00035006945832017   208.0   36.0  7488.0
696  C00035006945832017   208.0   37.0  7696.0
697  C00035006945832017   208.0   38.0  7904.0
701  C00117838600152017   211.0    1.0   211.0
728  C00193433968152017   100.0    1.0   100.0
771  C00193433222032017    15.0    1.0    15.0
773  C00193433947052017  1000.0    1.0  1000.0
782  C00193433973332017    50.0    1.0    50.0
807  C00193433947082017    40.0    1.0    40.0
841  C00193433855012017   173.0    1.0   173.0
853  C00193433200152017   100.0    1.0   100.0
854  C00193433968152017    65.0    2.0   150.0
883  C00193433105162017   250.0    1.0   250.0
916  C00193433857182017   300.0    1.0   300.0
943  C00193433292052017   150.0    1.0   150.0
944  C00193433112182017   100.0    1.0   100.0
946  C00193433615252017    50.0    1.0    50.0
956  C00193433917022017   250.0    1.0   250.0
961  C00193433947082017    44.2    2.0    94.0
966  C00193433940252017    41.0    1.0    41.0
980  C00193433615252017    32.5    2.0    75.0
981  C00193433615252017    25.0    3.0   100.0
993  C00193433770062017    25.0    1.0    25.0
994  C00193433105162017   250.0    2.0   500.0

[104 rows x 4 columns]

In [16]:
start_time = timeit.default_timer()

dd = defaultdict(list)
dataset_final = dataset_arrange.to_dict('records', into=dd)

d1 = defaultdict(list)
d2 = defaultdict(list)
perc = 30.
percent = perc/100.



for item in dataset_final:
    identity=item['Identity']
    amount=item['TRANS_AMT']
    index1=item['index1']
    d1[identity].append(amount)
    if len(d1[identity]) ==1:
        perc_of_cont = amount
        total_cont = amount
        time_of_cont =1
        continue
    else:
        ranked = sorted(d1[identity])
        n = int(round(percent * len(d1[identity])))
        perc_of_cont=ranked[n-1]
        total_cont=sum(d1[identity])
        time_of_cont=len(d1[identity])
    

    d2[index1].append(identity)
    d2[index1].append(perc_of_cont)
    d2[index1].append(total_cont)
    d2[index1].append(time_of_cont)    
    
elapsed = timeit.default_timer() - start_time
print (elapsed)

    
#for k, v in d1.items():       
#    print (k,v)

0.0037412410019896924

In [ ]:
#%timeit dataset_final.items()

In [ ]:
# group by and sum
# https://stackoverflow.com/questions/33823091/python-pandas-counting-the-frequency-of-a-specific-value-in-each-row-of-datafra
# https://stackoverflow.com/questions/42446006/pandas-find-previous-row-of-matching-value
#data_output['TRANS_AMT_PRE'] = \
#data_output.groupby(['CMTE_ID','ZIP_CODE','TRANS_DT'])['TRANS_AMT'].shift()
#data_output['TRANS_AMT'] + \
#data_output.groupby('ZIP_CODE')['TRANS_AMT'].shift()

In [ ]:
#grouped=data_output.groupby(['CMTE_ID','ZIP_CODE','TRANS_DT'])

In [ ]:
#new=data_output.groupby(['CMTE_ID']).get_group('C00035006')
#grouped.agg({'TRANS_AMT':np.sum,'TRANS_AMT': np.mean})

In [ ]:
#for name, group in grouped:
    #print(name)
#    print(group.TRANS_AMT)

In [ ]:
#grouped.bfill